with report as (
    select 
    SAFE_CAST(campaign_id as STRING) as campaign_id,
    units_sold_clicks_7_d as units_sold_clicks_7d  ,
    units_sold_same_sku_1_d as units_sold_same_sku_1d  ,
    sales_7_d as sales_7d  ,
    purchases_same_sku_7_d as purchases_same_sku_7d  ,
    attributed_sales_same_sku_30_d as attributed_sales_same_sku_30d  ,
    spend ,
    units_sold_other_sku_7_d as units_sold_other_sku_7d  ,
    SAFE_CAST(ad_id as STRING) as ad_id ,
    SAFE_CAST(ad_group_id as STRING) as adgroup_id ,
    units_sold_same_sku_14_d as units_sold_same_sku_14d  ,
    sales_14_d as sales_14d  ,
    units_sold_same_sku_7_d as units_sold_same_sku_7d  ,
    advertised_asin ,
    sales_30_d as sales_30d  ,
    clicks ,
    purchases_same_sku_14_d as purchases_same_sku_14d  ,
    purchases_same_sku_30_d as purchases_same_sku_30d  ,
    purchases_1_d as purchases_1d  ,
    attributed_sales_same_sku_7_d as attributed_sales_same_sku_7d  ,
    sales_1_d as sales_1d  ,
    campaign_budget_currency_code as currency,
    units_sold_clicks_30_d as units_sold_clicks_30d  ,
    units_sold_clicks_14_d as units_sold_clicks_14d  ,
    purchases_7_d as purchases_7d  ,
    attributed_sales_same_sku_1_d as attributed_sales_same_sku_1d  ,
    purchases_14_d as purchases_14d  ,
    impressions ,
    cost ,
    purchases_same_sku_1_d as purchases_same_sku_1d  ,
    purchases_30_d as purchases_30d  ,
    attributed_sales_same_sku_14_d as attributed_sales_same_sku_14d  ,
    SAFE_CAST( date AS DATE ) as day,
    units_sold_same_sku_30_d as units_sold_same_sku_30d  ,
    units_sold_clicks_1_d as units_sold_clicks_1d  ,
    sales_other_sku_7_d as sales_other_sku_7d  ,
    "sponsoredProducts" as campaign_type,
    from {{ source('dbt_amazon_ads','advertised_product_report')}}

)
select * from report
