version: 2

models:
  - name: amazon-ad_performance-sponsored_brandcampaign-v1
    config:
      schema: PUB_base
      materialized: incremental
      incremental_strategy: microbatch
      event_time: day 
      begin: 2025-01-01
      batch_size: day
      full_refresh: false
      partition_by:
        field: day
        data_type: date
        granularity: day


